### ISSUE TITLE
Lifetime of ephemeral ssh keys generated for ssh tunnels

### ISSUE THREAD

**Issue by lipmas** [bastionzero/zli#39]
Currently for each new ssh-proxy tunnel thoum will generate a unique ssh key and overwrite the thoum-managed ssh key file:

https://github.com/cwcrypto/thoum/blob/577c90a70ee84bf4fef0303de707dffc1155f29d/src/ssm-tunnel/ssm-tunnel.service.ts#L128-L140

We may want to relax this constraint in the future and allow the same key to be reused for the lifetime of a user login session.

Note even if we did this it would still require us to send the pubkey to the bastion via the `AddSshPubKey` websocket message for each new tunnel  because the bastion will only add the key to the target's `authorized_keys` file for 1 min before removing it. See implementation [here](https://github.com/cwcrypto/webshell-backend/blob/22353ff8bdf2d37b532344cc7339bd4d0871aa85/Webshell.WebApp/Services/SsmSendCommandService/SsmSendCommandService.cs#L30).

**Comment by johncmerfeld** [comment]
Resolved by #435
